
import re


DOMAIN = "cartelectronic_wes"

SENSOR_CLAMP_POWER_PATTERN = re.compile("(?:(?:(?P<va>\d+) VA)|(?:(?P<w>\d+) W cos phi (?P<cos_phi>\d.\d+)))")
SENSOR_ID_PREFIX = "wes_"

FILENAME_SENSOR_CGX = "homeassistant.cgx"

TIC_CONSUMPTION_INDEX_LABELS = ["BASE", "H_PLEINE", "EJPHN", "EJPHPM", "BBRHCJB", "BBRHPJB", "BBRHCJW", "BBRHPJW", "BBRHCJR", "BBRHPJR", "H_WeekEnd", "HC_Semaine", "HP_Semaine", "HC_WeekEnd", "HP_WeekEnd", "HC_Mercredi", "HP_Mercredi", "H_SUPER_CREUSE"]
TIC_PRODUCTION_INDEX_LABELS = ["PRODUCTEUR", "INJECTION"]
TIC_INDEX_LABELS = TIC_CONSUMPTION_INDEX_LABELS + TIC_PRODUCTION_INDEX_LABELS
TIC_SUBSCRIPTION_LABELS = ["OPTARIF", "ISOUSC", "PTEC", "DEMAIN"]
TIC_APPARENT_POWER_LABELS = ["PAP", "PAPIJ"]
TIC_INTENSITY_LABELS = ["IINST", "IINST1", "IINST2", "IINST3", "IMAX", "IMAX1", "IMAX2", "IMAX3"]
TIC_VOLTAGE_LABELS = ["TENSION1", "TENSION2", "TENSION3"]